<template>
  <n-icon :size="size" :class="iconClass">
    <component :is="resolvedIcon" />
  </n-icon>
</template>

<script setup>
import { computed } from 'vue'
import {
  AddOutline,
  AlertCircleOutline,
  AnalyticsOutline,
  ArchiveOutline,
  ArrowBackOutline,
  ArrowDownOutline,
  ArrowForwardOutline,
  ArrowUpOutline,
  BarChartOutline,
  BookOutline,
  CheckmarkCircleOutline,
  CheckmarkOutline,
  ChevronBackOutline,
  ChevronForwardOutline,
  CloudDoneOutline,
  CloudUploadOutline,
  CloseCircleOutline,
  CloseOutline,
  CodeSlashOutline,
  CubeOutline,
  CreateOutline,
  DocumentAttachOutline,
  DocumentTextOutline,
  DownloadOutline,
  EyeOffOutline,
  EyeOutline,
  FitnessOutline,
  FlaskOutline,
  GridOutline,
  HappyOutline,
  HeartOutline,
  HelpCircleOutline,
  InformationCircleOutline,
  ListCircleOutline,
  ListOutline,
  MenuOutline,
  MoonOutline,
  PawOutline,
  PeopleOutline,
  PlayCircleOutline,
  QrCodeOutline,
  RefreshCircleOutline,
  RefreshOutline,
  RemoveCircleOutline,
  ReorderThreeOutline,
  SaveOutline,
  ScaleOutline,
  SearchOutline,
  SettingsOutline,
  SwapHorizontalOutline,
  SunnyOutline,
  TrashBinOutline,
  TrashOutline,
  TrendingDownOutline,
  WarningOutline,
  MaleOutline,
  FemaleOutline,
  MaleFemaleOutline,
  EllipsisHorizontalCircleOutline,
  FileTrayOutline
} from '@vicons/ionicons5'

const props = defineProps({
  name: {
    type: String,
    default: ''
  },
  size: {
    type: Number,
    default: 18
  },
  iconClass: {
    type: [String, Array, Object],
    default: ''
  }
})

const iconMap = {
  add: AddOutline,
  archive: ArchiveOutline,
  arrow_back: ArrowBackOutline,
  arrow_downward: ArrowDownOutline,
  arrow_upward: ArrowUpOutline,
  bar_chart: BarChartOutline,
  book: BookOutline,
  cage: CubeOutline,
  cancel: CloseCircleOutline,
  check: CheckmarkOutline,
  check_circle: CheckmarkCircleOutline,
  chevron_left: ChevronBackOutline,
  chevron_right: ChevronForwardOutline,
  cloud_done: CloudDoneOutline,
  cloud_upload: CloudUploadOutline,
  close: CloseOutline,
  code: CodeSlashOutline,
  delete: TrashOutline,
  delete_forever: TrashBinOutline,
  download: DownloadOutline,
  drag_handle: ReorderThreeOutline,
  edit: CreateOutline,
  fitness_outline: FitnessOutline,
  error: AlertCircleOutline,
  error_outline: AlertCircleOutline,
  flask: FlaskOutline,
  happy: HappyOutline,
  heart: HeartOutline,
  format_list_bulleted: ListOutline,
  grid_view: GridOutline,
  group: PeopleOutline,
  inbox: ArchiveOutline,
  info: InformationCircleOutline,
  insights: AnalyticsOutline,
  menu: MenuOutline,
  dark_mode: MoonOutline,
  menu_book: BookOutline,
  monitor_weight: ScaleOutline,
  note_add: DocumentTextOutline,
  pets: PawOutline,
  picture_as_pdf: DocumentAttachOutline,
  play_circle: PlayCircleOutline,
  playlist_add: ListCircleOutline,
  qr_code_2: QrCodeOutline,
  refresh: RefreshOutline,
  remove_circle: RemoveCircleOutline,
  replay: RefreshCircleOutline,
  save: SaveOutline,
  scale: ScaleOutline,
  search: SearchOutline,
  settings: SettingsOutline,
  swap_horiz: SwapHorizontalOutline,
  light_mode: SunnyOutline,
  table_chart: GridOutline,
  trending_down: TrendingDownOutline,
  view_sidebar: GridOutline,
  visibility: EyeOutline,
  visibility_off: EyeOffOutline,
  warning: WarningOutline,
  arrow_forward: ArrowForwardOutline,
  male: MaleOutline,
  female: FemaleOutline,
  male_female: MaleFemaleOutline,
  more_horiz_circle: EllipsisHorizontalCircleOutline,
  help: HelpCircleOutline,
  file_tray: FileTrayOutline,
  keyboard_arrow_up: FileTrayOutline
}

const resolvedIcon = computed(() => {
  const normalized = (props.name || '').trim().toLowerCase()
  return iconMap[normalized] || HelpCircleOutline
})
</script>
